### ISSUE TITLE
Autoload doesn't work

### ISSUE THREAD

**Issue by IslandUsurper** [Mozu/mozu-php-sdk#14]
57b9647881c4f748b39e0bc9ecbf26aac40ec7f7 changed the autoload setting in composer.json from psr-0 to psr-4, but it didn't change the folder structure in src/ to reflect this change. Now, anyone using v1.17.0 or later is going to wonder why it doesn't work.

Considering that Composer installs this package in `vendor/mozu/api`, I would suggest changing composer.json to say
```
"psr-4": {
    "Mozu\\Api\\": "src/"
}
```
and remove the `Mozu/` and `Api/` directory levels from `src/`. Then, it makes sense to find `ProductResource` in `vendor/mozu/api/src/Resources/Commerce/Catalog/Admin/ProductResource.php`.

**Comment by sanjaymandadi** [comment]
We have update the folder structure match PSR-4 specifications and published 1.17.1 package.
